"""empty message

Revision ID: 082472f78964
Revises: 24695d2ee51c
Create Date: 2024-06-13 11:42:43.135254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082472f78964'
down_revision = '24695d2ee51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    # ### end Alembic commands ###
