"""empty message

Revision ID: 24695d2ee51c
Revises: 505ea4c9132e
Create Date: 2024-06-13 02:25:51.713396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24695d2ee51c'
down_revision = '505ea4c9132e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
