"""empty message

Revision ID: 505ea4c9132e
Revises: c4c069118cef
Create Date: 2024-06-13 02:09:20.632132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505ea4c9132e'
down_revision = 'c4c069118cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
